- hosts: localhost
  gather_facts: no
  # Encrypted ansible variable files housing the variables:
  #  - vaulted_atlas_public_key
  #  - vaulted_atlas_private_key
  #  - vaulted_db_password
  #  - vaulted_atlas_project_id
  vars_files:
    - ../credentials/atlas_creds.yml
    - ../credentials/atlas_org_details.yml

  tasks:

    - name: Query Atlas cluster info using curl
      ansible.builtin.shell: |
        curl --user "{{ vaulted_atlas_public_key }}:{{ vaulted_atlas_private_key }}" \
            --digest \
            -H "Accept: application/vnd.atlas.2025-03-12+json" \
            -H "Content-Type: application/json" \
            -X GET \
            -d '{}' \
            "https://cloud.mongodb.com/api/atlas/v2/groups/{{ vaulted_atlas_project_id }}/clusters" \
            | tee clusters_and_members.json
      args:
        chdir: "{{ playbook_dir }}"
      register: atlas_response
      changed_when: false
      failed_when: "'Unauthorized' in atlas_response.stdout"

    - name: Save pretty-printed Atlas response to clusters_and_members.json using jq
      ansible.builtin.shell: |
        echo '{{ atlas_response.stdout }}' | jq . > clusters_and_members.json
      args:
        chdir: "{{ playbook_dir }}"

    - name: Extract hostnames per cluster from clusters_and_members.json
      ansible.builtin.shell: |
        jq -r '.results[] | "\(.name) \(.connectionStrings.standard)"' clusters_and_members.json \
        | while read -r name connstr; do
            hosts=$(echo "$connstr" \
              | sed 's/^mongodb:\/\///' \
              | sed 's/\?.*//' \
              | tr ',' '\n' \
              | cut -d':' -f1)
            echo "Cluster: $name"
            echo "$hosts"
            echo "---"
          done
      args:
        chdir: "{{ playbook_dir }}"
      register: parsed_clusters

    - name: Display all clusters and their hostnames
      ansible.builtin.debug:
        msg: "{{ parsed_clusters.stdout_lines }}"