---
collections:
  - name: community.mongodb
    version: 1.7.10
  - name: community.general
    version: 11.0.0
  - name: ansible.posix
    version: 2.0.0
  - name: cloud.terraform
    version: 3.1.0
